# Generated by Django 2.2.1 on 2019-05-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='titulo',
            new_name='title',
        ),
    ]
